# Cloudflare Workers 配置檔案
# 用於部署 Sheet Order Dashboard API

name = "sheet-order-api"
main = "index.js"
compatibility_date = "2025-08-03"

# 設定自定義域名 (可選)
# routes = [
#   { pattern = "api.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]

# 生產環境設定
[env.production]
name = "sheet-order-api"

[[env.production.kv_namespaces]]
binding = "CACHE_KV"
id = "37c85c7f1aa84365810dc5ddb4015d47"

[env.production.vars]
GOOGLE_SHEET_ID = "10MMALrfBonchPGjb-ps6Knw7MV6lllrrKRCTeafCIuo"
APP_ENV = "production"
CACHE_DURATION = "15000"
DEBUG_MODE = "false"

# 開發環境設定
[env.development]
name = "sheet-order-api-dev"

[[env.development.kv_namespaces]]
binding = "CACHE_KV"
id = "9e131cdce1674b5e946c19ece9efef0c"

[env.development.vars]
GOOGLE_SHEET_ID = "10MMALrfBonchPGjb-ps6Knw7MV6lllrrKRCTeafCIuo"
APP_ENV = "development"
CACHE_DURATION = "5000"
DEBUG_MODE = "true"

# Secrets 設定說明
# 使用以下命令設定敏感資訊：
# wrangler secret put GOOGLE_SERVICE_ACCOUNT_KEY
# 將 service-account-key2.json 的完整內容複製貼上